// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradusApp.Infrastructure.Persistence;

#nullable disable

namespace TradusApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradusAppDbContext))]
    [Migration("20251107004449_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradusApp.Domain.Entities.Capitulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LibroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LibroId", "Numero")
                        .IsUnique();

                    b.ToTable("Capitulos", (string)null);
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CapituloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CapituloId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas", (string)null);
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Libro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("CalificacionPromedio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2, 1)
                        .HasColumnType("decimal(2,1)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Libros", (string)null);
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.LibroEtiqueta", b =>
                {
                    b.Property<Guid>("LibroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EtiquetaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LibroId", "EtiquetaId");

                    b.HasIndex("EtiquetaId");

                    b.ToTable("LibroEtiquetas", (string)null);
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Capitulo", b =>
                {
                    b.HasOne("TradusApp.Domain.Entities.Libro", "Libro")
                        .WithMany("Capitulos")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Comment", b =>
                {
                    b.HasOne("TradusApp.Domain.Entities.Capitulo", "Capitulo")
                        .WithMany("Comments")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitulo");
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.LibroEtiqueta", b =>
                {
                    b.HasOne("TradusApp.Domain.Entities.Etiqueta", "Etiqueta")
                        .WithMany("LibroEtiquetas")
                        .HasForeignKey("EtiquetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TradusApp.Domain.Entities.Libro", "Libro")
                        .WithMany("LibroEtiquetas")
                        .HasForeignKey("LibroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etiqueta");

                    b.Navigation("Libro");
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Capitulo", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Etiqueta", b =>
                {
                    b.Navigation("LibroEtiquetas");
                });

            modelBuilder.Entity("TradusApp.Domain.Entities.Libro", b =>
                {
                    b.Navigation("Capitulos");

                    b.Navigation("LibroEtiquetas");
                });
#pragma warning restore 612, 618
        }
    }
}
